apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: bit-2503
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  type: ClusterIP
  ports:
    - name: http-chat
      protocol: TCP
      port: 8083
      targetPort: 8083
